#!/usr/bin/env bash
# =============================================================================
# Demo deploy helper — Firebase Hosting + Cloudflare Tunnel (임시 URL)
# =============================================================================
# 사용:
#   ./scripts/deploy_demo.sh <TUNNEL_URL>
#   예) ./scripts/deploy_demo.sh https://abc-def-ghi.trycloudflare.com
#
# 동작:
#   1. dashboard-web/.env.production 갱신 (NEXT_PUBLIC_*_API)
#   2. 루트 .env CORS_ORIGINS / NLP_API_CORS_ORIGINS 에 Tunnel/Firebase 도메인 추가
#   3. 백엔드(lunch-api, nlp-api) 재기동
#   4. 정적 빌드 (NEXT_OUTPUT=export)
#   5. Firebase Hosting 배포
#
# 전제:
#   - cloudflared 가 별도 터미널에서 quick tunnel 실행 중이어야 함:
#       cloudflared tunnel --url https://localhost:443 --no-tls-verify
#   - firebase CLI 로그인됨 (firebase login)
#   - dashboard-web/.firebaserc 에 프로젝트 ID 설정됨
#   - .env 의 NEXT_PUBLIC_KAKAO_MAP_KEY 등 시크릿이 채워져 있어야 함
# =============================================================================
set -euo pipefail

# -----------------------------------------------------------------------------
# Args & 사전 검사
# -----------------------------------------------------------------------------
TUNNEL_URL="${1:-}"

if [[ -z "${TUNNEL_URL}" ]]; then
  echo "[error] Tunnel URL 필수." >&2
  echo "" >&2
  echo "Usage: $0 <TUNNEL_URL>" >&2
  echo "" >&2
  echo "별도 터미널에서 먼저:" >&2
  echo "  cloudflared tunnel --url https://localhost:443 --no-tls-verify" >&2
  echo "" >&2
  echo "출력에 표시된 https://*.trycloudflare.com URL 을 인자로 전달." >&2
  exit 1
fi

# URL 형식 검증
if [[ ! "${TUNNEL_URL}" =~ ^https://[a-z0-9-]+\.trycloudflare\.com$ ]]; then
  echo "[warn] URL이 https://*.trycloudflare.com 형식이 아님: ${TUNNEL_URL}" >&2
  echo "[warn] 영구 도메인 사용 시 정상 — 계속 진행" >&2
fi

# 프로젝트 루트 (스크립트 위치 기준)
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "${ROOT}"

cecho() { printf "\033[1;32m[deploy]\033[0m %s\n" "$*"; }
werr()  { printf "\033[1;31m[deploy]\033[0m %s\n" "$*" >&2; }

# 의존 명령 검사
for cmd in firebase npm docker sed; do
  if ! command -v "${cmd}" > /dev/null 2>&1; then
    werr "[fatal] '${cmd}' 명령을 찾지 못함. 설치 후 재실행."
    exit 1
  fi
done

# .firebaserc 존재 확인
if [[ ! -f "dashboard-web/.firebaserc" ]]; then
  werr "[fatal] dashboard-web/.firebaserc 없음."
  werr "  cp dashboard-web/.firebaserc.example dashboard-web/.firebaserc"
  werr "  편집 후 'default' 키에 본인 Firebase 프로젝트 ID 입력"
  exit 1
fi

# Firebase 프로젝트 ID 추출 (Firebase Hosting 도메인 추론용)
PROJECT_ID=$(grep -oE '"default": *"[^"]+"' dashboard-web/.firebaserc | head -1 | sed -E 's/.*"([^"]+)"$/\1/')
if [[ -z "${PROJECT_ID}" || "${PROJECT_ID}" == "your-firebase-project-id" ]]; then
  werr "[fatal] dashboard-web/.firebaserc 의 프로젝트 ID가 placeholder."
  werr "  실제 Firebase 프로젝트 ID로 수정 후 재실행"
  exit 1
fi
FIREBASE_HOST="https://${PROJECT_ID}.web.app"

cecho "Tunnel URL  : ${TUNNEL_URL}"
cecho "Firebase    : ${FIREBASE_HOST}"
echo

# -----------------------------------------------------------------------------
# 1. dashboard-web/.env.production 갱신
# -----------------------------------------------------------------------------
cecho "[1/5] dashboard-web/.env.production 갱신"

# 기존 .env.production 백업
if [[ -f "dashboard-web/.env.production" ]]; then
  cp dashboard-web/.env.production dashboard-web/.env.production.bak
fi

# Kakao JavaScript SDK 키 — 루트 .env 우선, dashboard-web/.env.local 폴백
KAKAO_KEY=""
extract_key() {
  local file="$1"
  [[ -f "$file" ]] || return 0
  grep -E "^NEXT_PUBLIC_KAKAO_MAP_KEY=" "$file" | head -1 | cut -d= -f2- | tr -d '"' || true
}
KAKAO_KEY="$(extract_key .env)"
if [[ -z "${KAKAO_KEY}" ]]; then
  KAKAO_KEY="$(extract_key dashboard-web/.env.local)"
  if [[ -n "${KAKAO_KEY}" ]]; then
    cecho "  Kakao 키를 dashboard-web/.env.local 에서 가져옴"
  fi
fi
if [[ -z "${KAKAO_KEY}" ]]; then
  werr "  ⚠ NEXT_PUBLIC_KAKAO_MAP_KEY 가 비어있음 — 지도 미동작"
else
  cecho "  Kakao 키 (앞 6자): ${KAKAO_KEY:0:6}..."
fi

cat > dashboard-web/.env.production <<EOF
# Auto-generated by scripts/deploy_demo.sh — do not edit manually
# NLP_API 는 /nlp prefix 없이 호스트만 — api.ts 가 path 에 /nlp/health 등을 덧붙임.
# (이중 prefix /nlp/nlp/* 방지)
NEXT_PUBLIC_LUNCH_API=${TUNNEL_URL}/api
NEXT_PUBLIC_NLP_API=${TUNNEL_URL}
NEXT_PUBLIC_DEFAULT_USER_ID=1
NEXT_PUBLIC_KAKAO_MAP_KEY=${KAKAO_KEY}
EOF

# -----------------------------------------------------------------------------
# 2. 루트 .env CORS 갱신
# -----------------------------------------------------------------------------
cecho "[2/5] 백엔드 CORS 화이트리스트 갱신"

if [[ ! -f ".env" ]]; then
  werr "[fatal] .env 없음. cp .env.example .env 후 시크릿 입력"
  exit 1
fi
cp .env .env.bak

# 기존 origins 보존 + Tunnel + Firebase 도메인 추가 (중복 제거)
update_cors_var() {
  local var_name="$1"
  local existing
  existing=$(grep -E "^${var_name}=" .env | head -1 | cut -d= -f2- || true)
  if [[ -z "${existing}" ]]; then
    existing="http://localhost:3000"
  fi
  # 콤마 구분 → 줄바꿈 → 정렬+중복제거 → 콤마 재결합
  local merged
  merged=$(printf "%s\n%s\n%s\n" \
    "$(echo "${existing}" | tr ',' '\n')" \
    "${TUNNEL_URL}" \
    "${FIREBASE_HOST}" \
    | sed '/^$/d' | sort -u | paste -sd, -)
  if grep -qE "^${var_name}=" .env; then
    sed -i.tmp -E "s|^${var_name}=.*|${var_name}=${merged}|" .env
  else
    echo "${var_name}=${merged}" >> .env
  fi
  rm -f .env.tmp
  cecho "  ${var_name}=${merged}"
}

update_cors_var "CORS_ORIGINS"
update_cors_var "NLP_API_CORS_ORIGINS"

# Kakao Maps 도메인 등록 (참고)
if grep -qE "^KAKAO_KA_ORIGIN=" .env; then
  sed -i.tmp -E "s|^KAKAO_KA_ORIGIN=.*|KAKAO_KA_ORIGIN=${FIREBASE_HOST}|" .env
  rm -f .env.tmp
  cecho "  KAKAO_KA_ORIGIN=${FIREBASE_HOST}"
fi

# -----------------------------------------------------------------------------
# 3. 백엔드 재기동 (force-recreate 으로 새 CORS 반영)
# -----------------------------------------------------------------------------
cecho "[3/5] 백엔드 재기동"
docker compose --profile proxy up -d --force-recreate lunch-api nlp-api > /dev/null
cecho "  대기 (10s) — health check 안정화"
sleep 10
docker compose ps --format "  {{.Name}}\t{{.Status}}" | grep -E "lunch-api|nlp-api" || true

# -----------------------------------------------------------------------------
# 4. 정적 빌드
# -----------------------------------------------------------------------------
cecho "[4/5] 정적 빌드 (NEXT_OUTPUT=export)"
# Next.js env 우선순위: process.env > .env.$(NODE_ENV).local > .env.local > .env.$(NODE_ENV) > .env
# CLI 로 env 변수를 직접 주입해야 .env.local 이 덮어쓰지 못함.
cd dashboard-web
rm -rf out
NEXT_OUTPUT=export \
  NEXT_PUBLIC_LUNCH_API="${TUNNEL_URL}/api" \
  NEXT_PUBLIC_NLP_API="${TUNNEL_URL}" \
  NEXT_PUBLIC_DEFAULT_USER_ID=1 \
  NEXT_PUBLIC_KAKAO_MAP_KEY="${KAKAO_KEY}" \
  npm run build
cd ..

# -----------------------------------------------------------------------------
# 5. Firebase Hosting 배포
# -----------------------------------------------------------------------------
cecho "[5/5] Firebase Hosting 배포"
cd dashboard-web
firebase deploy --only hosting --non-interactive
cd ..

echo
cecho "✅ 배포 완료"
echo
echo "  Frontend : ${FIREBASE_HOST}"
echo "  Backend  : ${TUNNEL_URL} (cloudflared 가 살아있는 동안만 유효)"
echo
echo "검증:"
echo "  curl ${TUNNEL_URL}/api/health"
echo "  curl ${TUNNEL_URL}/nlp/health"
echo "  open ${FIREBASE_HOST}"
echo
echo "주의:"
echo "  - cloudflared 프로세스가 종료되면 백엔드 외부 접근 불가"
echo "  - Tunnel URL이 변경되면 본 스크립트 재실행 필요"
